<?php

/**
 * WARNING: This is a generated wrapper file.
 * Do not edit this file manually as changes will be overwritten
 * by the wrapper generator (generate_wrappers.php).
 * 
 * To modify this class, edit the corresponding Core class in src/Core/
 * and regenerate the wrappers.
 */

namespace MintyPHP;

use MintyPHP\Core\Analyzer as CoreAnalyzer;

/**
 * Analyzer class for checking PHP files for disallowed output functions.
 * 
 * This class analyzes action and view files to ensure they don't contain
 * direct output functions like echo, print, var_dump, etc., which could
 * break the MVC pattern by mixing logic with output.
 */
class Analyzer
{
    /**
     * The Analyzer instance
     * @var ?CoreAnalyzer
     */
    private static ?CoreAnalyzer $instance = null;

    /**
     * Get the Analyzer instance
     * @return CoreAnalyzer
     */
    public static function getInstance(): CoreAnalyzer
    {
        return self::$instance ??= new CoreAnalyzer(
            Router::getInstance()
        );
    }

    /**
     * Set the Analyzer instance to use
     * @param ?CoreAnalyzer $instance
     * @return void
     */
    public static function setInstance(?CoreAnalyzer $instance): void
    {
        self::$instance = $instance;
    }

    /**
    	 * Execute the analyzer to check all action and view files.
    	 * 
    	 * Checks template actions, actions, views, and template views for
    	 * disallowed output functions.
    	 * 
    	 * @return void
    	 */
    public static function execute(): void
    {
        $instance = self::getInstance();
        $instance->execute();
    }
}
