<?php

/**
 * WARNING: This is a generated wrapper file.
 * Do not edit this file manually as changes will be overwritten
 * by the wrapper generator (generate_wrappers.php).
 * 
 * To modify this class, edit the corresponding Core class in src/Core/
 * and regenerate the wrappers.
 */

namespace MintyPHP;

use MintyPHP\Core\Buffer as CoreBuffer;

/**
 * Static wrapper class for Buffer operations using a singleton pattern.
 */
class Buffer
{
    /**
     * The Buffer instance
     * @var ?CoreBuffer
     */
    private static ?CoreBuffer $instance = null;

    /**
     * Get the Buffer instance
     * @return CoreBuffer
     */
    public static function getInstance(): CoreBuffer
    {
        return self::$instance ??= new CoreBuffer(

        );
    }

    /**
     * Set the Buffer instance to use
     * @param CoreBuffer $instance
     * @return void
     */
    public static function setInstance(CoreBuffer $instance): void
    {
        self::$instance = $instance;
    }

    /**
     * Start a named output buffer.
     * 
     * Pushes the buffer name onto the stack and begins capturing output.
     * All output generated after this call will be captured until end()
     * is called with the same name.
     * 
     * @param string $name The name of the buffer to start.
     * @return void
     */
    public static function start(string $name): void
    {
        $instance = self::getInstance();
        $instance->start($name);
    }

    /**
     * End a named output buffer.
     * 
     * Stops capturing output for the named buffer and stores the captured
     * content. The buffer name must match the most recently started buffer
     * to maintain proper nesting.
     * 
     * @param string $name The name of the buffer to end.
     * @return void
     * @throws \Exception If the buffer name doesn't match the top of the stack.
     */
    public static function end(string $name): void
    {
        $instance = self::getInstance();
        $instance->end($name);
    }

    /**
     * Set the contents of a named buffer.
     * 
     * Directly assigns content to a buffer without using output buffering.
     * This overwrites any existing content for the buffer.
     * 
     * @param string $name The name of the buffer.
     * @param string $string The content to store in the buffer.
     * @return void
     */
    public static function set(string $name, string $string): void
    {
        $instance = self::getInstance();
        $instance->set($name, $string);
    }

    /**
     * Output the contents of a named buffer.
     * 
     * Echoes the stored content of the specified buffer if it exists.
     * 
     * @param string $name The name of the buffer to output.
     * @return bool True if the buffer exists and was output, false otherwise.
     */
    public static function get(string $name): bool
    {
        $instance = self::getInstance();
        return $instance->get($name);
    }
}
