<?php

/**
 * WARNING: This is a generated wrapper file.
 * Do not edit this file manually as changes will be overwritten
 * by the wrapper generator (generate_wrappers.php).
 * 
 * To modify this class, edit the corresponding Core class in src/Core/
 * and regenerate the wrappers.
 */

namespace MintyPHP;

use MintyPHP\Core\Cache as CoreCache;

/**
 * Cache layer for MintyPHP using Memcached
 * 
 * Provides caching operations with support for debugging and monitoring.
 */
class Cache
{
    /**
     * Static configuration parameters
     */
    public static string $prefix = 'mintyphp';
    public static string $servers = '127.0.0.1';

    /**
     * The Cache instance
     * @var ?CoreCache
     */
    private static ?CoreCache $instance = null;

    /**
     * Get the Cache instance
     * @return CoreCache
     */
    public static function getInstance(): CoreCache
    {
        return self::$instance ??= new CoreCache(
            null,
            self::$prefix,
            self::$servers
        );
    }

    /**
     * Set the Cache instance to use
     * @param CoreCache $instance
     * @return void
     */
    public static function setInstance(CoreCache $instance): void
    {
        self::$instance = $instance;
    }

    /**
     * Add a value to the cache only if it doesn't already exist
     *
     * @param string $key The cache key
     * @param mixed $var The value to store
     * @param int $expire Expiration time in seconds (0 = never expire)
     * @return bool True on success, false on failure
     */
    public static function add(string $key, mixed $var, int $expire = 0): bool
    {
        $instance = self::getInstance();
        return $instance->add($key, $var, $expire);
    }

    /**
     * Decrement a numeric value in the cache
     *
     * @param string $key The cache key
     * @param int $value The amount to decrement by (default: 1)
     * @return int|false The new value on success, false on failure
     */
    public static function decrement(string $key, int $value = 1): int|false
    {
        $instance = self::getInstance();
        return $instance->decrement($key, $value);
    }

    /**
     * Delete a value from the cache
     *
     * @param string $key The cache key
     * @return bool True on success, false on failure
     */
    public static function delete(string $key): bool
    {
        $instance = self::getInstance();
        return $instance->delete($key);
    }

    /**
     * Retrieve a value from the cache
     *
     * @param string $key The cache key
     * @return mixed The cached value, or false if not found
     */
    public static function get(string $key): mixed
    {
        $instance = self::getInstance();
        return $instance->get($key);
    }

    /**
     * Increment a numeric value in the cache
     *
     * @param string $key The cache key
     * @param int $value The amount to increment by (default: 1)
     * @return int|false The new value on success, false on failure
     */
    public static function increment(string $key, int $value = 1): int|false
    {
        $instance = self::getInstance();
        return $instance->increment($key, $value);
    }

    /**
     * Replace a value in the cache only if it already exists
     *
     * @param string $key The cache key
     * @param mixed $var The value to store
     * @param int $expire Expiration time in seconds (0 = never expire)
     * @return bool True on success, false on failure
     */
    public static function replace(string $key, mixed $var, int $expire = 0): bool
    {
        $instance = self::getInstance();
        return $instance->replace($key, $var, $expire);
    }

    /**
     * Store a value in the cache (creates or updates)
     *
     * @param string $key The cache key
     * @param mixed $var The value to store
     * @param int $expire Expiration time in seconds (0 = never expire)
     * @return bool True on success, false on failure
     */
    public static function set(string $key, mixed $var, int $expire = 0): bool
    {
        $instance = self::getInstance();
        return $instance->set($key, $var, $expire);
    }
}
