<?php

/**
 * WARNING: This is a generated wrapper file.
 * Do not edit this file manually as changes will be overwritten
 * by the wrapper generator (generate_wrappers.php).
 * 
 * To modify this class, edit the corresponding Core class in src/Core/
 * and regenerate the wrappers.
 */

namespace MintyPHP;

use MintyPHP\Core\Curl as CoreCurl;

/**
 * HTTP client for making cURL requests
 * 
 * Provides methods for making HTTP requests with support for caching,
 * redirects, cookies, and various HTTP methods.
 */
class Curl
{
    /** @var array<string,mixed> */
    public static array $options = [];
    /** @var array<string,string> */
    public static array $headers = [];
    public static bool $cookies = false;

    /**
     * The Curl instance
     * @var ?CoreCurl
     */
    private static ?CoreCurl $instance = null;

    /**
     * Get the Curl instance
     * @return CoreCurl
     */
    public static function getInstance(): CoreCurl
    {
        return self::$instance ??= new CoreCurl(
            self::$options,
            self::$headers,
            self::$cookies,
            null
        );
    }

    /**
     * Set the Curl instance to use
     * @param CoreCurl $instance
     * @return void
     */
    public static function setInstance(CoreCurl $instance): void
    {
        self::$instance = $instance;
    }

    /**
     * Make a cached HTTP request with automatic redirects
     * 
     * @param int $expire Cache expiration time in seconds
     * @param string $method HTTP method (GET, POST, etc.)
     * @param string $url The URL to request
     * @param string|array<mixed> $data Request data
     * @param array<string,string> $headers Additional headers
     * @param array<string,mixed> $options Additional cURL options
     * @return array<string,mixed> Response array with status, headers, data, and url
     */
    public static function navigateCached(int $expire, string $method, string $url, mixed $data, array $headers = [], array $options = []): array
    {
        $instance = self::getInstance();
        return $instance->navigateCached($expire, $method, $url, $data, $headers, $options);
    }

    /**
     * Make a cached HTTP request
     * 
     * @param int $expire Cache expiration time in seconds
     * @param string $method HTTP method (GET, POST, etc.)
     * @param string $url The URL to request
     * @param string|array<mixed> $data Request data
     * @param array<string,string> $headers Additional headers
     * @param array<string,mixed> $options Additional cURL options
     * @return array<string,mixed> Response array with status, headers, data, and url
     */
    public static function callCached(int $expire, string $method, string $url, mixed $data, array $headers = [], array $options = []): array
    {
        $instance = self::getInstance();
        return $instance->callCached($expire, $method, $url, $data, $headers, $options);
    }

    /**
     * Make an HTTP request with automatic redirects
     * 
     * @param string $method HTTP method (GET, POST, etc.)
     * @param string $url The URL to request
     * @param string|array<mixed> $data Request data
     * @param array<string,string> $headers Additional headers
     * @param array<string,mixed> $options Additional cURL options
     * @return array<string,mixed> Response array with status, headers, data, and url
     */
    public static function navigate(string $method, string $url, $data = '', array $headers = [], array $options = []): array
    {
        $instance = self::getInstance();
        return $instance->navigate($method, $url, $data, $headers, $options);
    }

    /**
     * Make an HTTP request
     * 
     * @param string $method HTTP method (GET, POST, etc.)
     * @param string $url The URL to request
     * @param string|array<mixed> $data Request data
     * @param array<string,string> $headers Additional headers
     * @param array<string,mixed> $options Additional cURL options
     * @return array<string,mixed> Response array with status, headers, data, and url
     */
    public static function call(string $method, string $url, $data = '', array $headers = [], array $options = []): array
    {
        $instance = self::getInstance();
        return $instance->call($method, $url, $data, $headers, $options);
    }
}
