<?php

/**
 * WARNING: This is a generated wrapper file.
 * Do not edit this file manually as changes will be overwritten
 * by the wrapper generator (generate_wrappers.php).
 * 
 * To modify this class, edit the corresponding Core class in src/Core/
 * and regenerate the wrappers.
 */

namespace MintyPHP;

use MintyPHP\Core\DB as CoreDB;

/**
 * Database abstraction layer for MintyPHP
 * 
 * Provides a secure interface for database operations using mysqli with prepared statements.
 * Supports debugging, query logging, and automatic parameter binding.
 */
class DB
{
    /**
     * Static configuration parameters
     */
    public static ?string $host = null;
    public static ?string $username = null;
    public static ?string $password = null;
    public static ?string $database = null;
    public static ?int $port = null;
    public static ?string $socket = null;

    /**
     * The DB instance
     * @var ?CoreDB
     */
    private static ?CoreDB $instance = null;

    /**
     * Get the DB instance
     * @return CoreDB
     */
    public static function getInstance(): CoreDB
    {
        return self::$instance ??= new CoreDB(
            self::$host,
            self::$username,
            self::$password,
            self::$database,
            self::$port,
            self::$socket,
            null,
            Debugger::$enabled ? Debugger::getInstance() : null
        );
    }

    /**
     * Set the DB instance to use
     * @param CoreDB $instance
     * @return void
     */
    public static function setInstance(CoreDB $instance): void
    {
        self::$instance = $instance;
    }

    /**
     * Executes a query with optional debugging
     * 
     * @param string $query SQL query with ? placeholders
     * @param mixed ...$params Query parameters
     * @return mixed Query result (array for SELECT, int for INSERT/UPDATE/DELETE)
     * @throws \RuntimeException if query execution fails or database is closed
     */
    public static function query(string $query, mixed ...$params): mixed
    {
        $instance = self::getInstance();
        return $instance->query($query, ...$params);
    }

    /**
     * Executes an INSERT query and returns the last insert ID
     * 
     * @param string $query SQL INSERT query
     * @param mixed ...$params Query parameters
     * @return int Last insert ID
     * @throws \RuntimeException if query execution fails or database is closed
     */
    public static function insert(string $query, mixed ...$params): int
    {
        $instance = self::getInstance();
        return $instance->insert($query, ...$params);
    }

    /**
     * Executes an UPDATE query and returns affected rows
     * 
     * @param string $query SQL UPDATE query
     * @param mixed ...$params Query parameters
     * @return int Number of affected rows
     * @throws \RuntimeException if query execution fails or database is closed
     */
    public static function update(string $query, mixed ...$params): int
    {
        $instance = self::getInstance();
        return $instance->update($query, ...$params);
    }

    /**
     * Executes a DELETE query and returns affected rows
     * 
     * @param string $query SQL DELETE query
     * @param mixed ...$params Query parameters
     * @return int Number of affected rows
     * @throws \RuntimeException if query execution fails or database is closed
     */
    public static function delete(string $query, mixed ...$params): int
    {
        $instance = self::getInstance();
        return $instance->delete($query, ...$params);
    }

    /**
     * Executes a SELECT query and returns all rows
     * 
     * @param string $query SQL SELECT query
     * @param mixed ...$params Query parameters
     * @return array<int, array<string, array<string, mixed>>> Array of result rows
     * @throws \RuntimeException if query execution fails or database is closed
     */
    public static function select(string $query, mixed ...$params): array
    {
        $instance = self::getInstance();
        return $instance->select($query, ...$params);
    }

    /**
     * Executes a SELECT query and returns the first row
     * 
     * @param string $query SQL SELECT query
     * @param mixed ...$params Query parameters
     * @return array<string, array<string, mixed>>|false First result row or false if no result
     * @throws \RuntimeException if query execution fails or database is closed
     */
    public static function selectOne(string $query, mixed ...$params): array|false
    {
        $instance = self::getInstance();
        return $instance->selectOne($query, ...$params);
    }

    /**
     * Executes a SELECT query and returns a single value
     * 
     * @param string $query SQL SELECT query
     * @param mixed ...$params Query parameters
     * @return mixed Single value from first column of first row, or false if no result
     * @throws \RuntimeException if query execution fails or database is closed
     */
    public static function selectValue(string $query, mixed ...$params): mixed
    {
        $instance = self::getInstance();
        return $instance->selectValue($query, ...$params);
    }

    /**
     * Executes a SELECT query and returns an array of values from first column
     * 
     * @param string $query SQL SELECT query
     * @param mixed ...$params Query parameters
     * @return array<int, mixed> Array of values from first column
     * @throws \RuntimeException if query execution fails or database is closed
     */
    public static function selectValues(string $query, mixed ...$params): array
    {
        $instance = self::getInstance();
        return $instance->selectValues($query, ...$params);
    }

    /**
     * Executes a SELECT query and returns key-value pairs
     * 
     * @param string $query SQL SELECT query returning at least 2 columns
     * @param mixed ...$params Query parameters
     * @return array<int|string, mixed> Associative array using first column as keys, second as values
     * @throws \RuntimeException if query execution fails or database is closed
     */
    public static function selectPairs(string $query, mixed ...$params): array
    {
        $instance = self::getInstance();
        return $instance->selectPairs($query, ...$params);
    }

    /**
     * Closes the database connection
     * 
     * @return void
     */
    public static function close(): void
    {
        $instance = self::getInstance();
        $instance->close();
    }

    /**
     * Returns the mysqli handle for advanced operations (undocumented)
     * 
     * @return \mysqli|null Database connection handle
     */
    public static function handle(): ?\mysqli
    {
        $instance = self::getInstance();
        return $instance->handle();
    }
}
