<?php

/**
 * WARNING: This is a generated wrapper file.
 * Do not edit this file manually as changes will be overwritten
 * by the wrapper generator (generate_wrappers.php).
 * 
 * To modify this class, edit the corresponding Core class in src/Core/
 * and regenerate the wrappers.
 */

namespace MintyPHP;

use MintyPHP\Core\Debugger as CoreDebugger;

/**
 * Debugger class for development and debugging support.
 * 
 * Provides comprehensive debugging capabilities including request logging,
 * query tracking, session inspection, and performance monitoring.
 */
class Debugger
{
    /**
     * Static configuration parameters
     */
    public static int $history = 10;
    public static bool $enabled = false;
    public static string $sessionKey = 'debugger';

    /**
     * The Debugger instance
     * @var ?CoreDebugger
     */
    private static ?CoreDebugger $instance = null;

    /**
     * Get the Debugger instance
     * @return CoreDebugger
     */
    public static function getInstance(): CoreDebugger
    {
        return self::$instance ??= new CoreDebugger(
            self::$history,
            self::$enabled,
            self::$sessionKey
        );
    }

    /**
     * Set the Debugger instance to use
     * @param CoreDebugger $instance
     * @return void
     */
    public static function setInstance(CoreDebugger $instance): void
    {
        self::$instance = $instance;
    }

    /**
     * Check if the Debugger is enabled
     * @return bool True if enabled, false otherwise
     */
    public static function isEnabled(): bool
    {
        $instance = self::getInstance();
        return $instance->isEnabled();
    }

    /**
     * Add a cache call entry to the debugger log
     * @param float $duration The duration of the cache call
     * @param string $command The cache command executed
     * @param array<mixed> $arguments The arguments passed to the cache command
     * @param mixed $result The result returned from the cache command
     * @return void
     */
    public static function addCacheCall(float $duration, string $command, array $arguments, mixed $result): void
    {
        $instance = self::getInstance();
        $instance->addCacheCall($duration, $command, $arguments, $result);
    }

    /**
     * Log the session state before processing the request
     * @return void
     */
    public static function logSessionBefore(): void
    {
        $instance = self::getInstance();
        $instance->logSessionBefore();
    }

    /**
     * Log the session state after processing the request
     * @return void
     */
    public static function logSessionAfter(): void
    {
        $instance = self::getInstance();
        $instance->logSessionAfter();
    }

    /**
     * Finalize and store the debugger data at the end of the request
     * @param string $type The type of request completion (e.g., 'ok', 'abort')
     * @return void
     */
    public static function end(string $type): void
    {
        $instance = self::getInstance();
        $instance->end($type);
    }

    /**
     * Output the debugger toolbar HTML.
     * @return void
     */
    public static function toolbar(): void
    {
        $instance = self::getInstance();
        $instance->toolbar();
    }

    /**
     * Debug a variable and return its string representation.
     * @param mixed $variable The variable to debug
     * @param int $strlen Maximum string length
     * @param int $width Maximum array/object width
     * @param int $depth Maximum depth for nested structures
     * @param int $i Current depth (used internally) 
     * @param array<object> $objects List of already processed objects (used internally)
     * @return string String representation of the variable
     */
    public static function debug(mixed $variable, int $strlen = 100, int $width = 25, int $depth = 10, int $i = 0, array &$objects = []): string
    {
        $instance = self::getInstance();
        return $instance->debug($variable, $strlen, $width, $depth, $i, $objects);
    }
}
