<?php

/**
 * WARNING: This is a generated wrapper file.
 * Do not edit this file manually as changes will be overwritten
 * by the wrapper generator (generate_wrappers.php).
 * 
 * To modify this class, edit the corresponding Core class in src/Core/
 * and regenerate the wrappers.
 */

namespace MintyPHP;

use MintyPHP\Core\Debugger as CoreDebugger;

/**
 * Debugger class for development and debugging support.
 * 
 * Provides comprehensive debugging capabilities including request logging,
 * query tracking, session inspection, and performance monitoring.
 */
class Debugger
{
    /**
     * Static configuration parameters
     */
    public static int $history = 10;
    public static bool $enabled = false;
    public static string $sessionKey = 'debugger';

    /**
     * The Debugger instance
     * @var ?CoreDebugger
     */
    private static ?CoreDebugger $instance = null;

    /**
     * Get the Debugger instance
     * @return CoreDebugger
     */
    public static function getInstance(): CoreDebugger
    {
        return self::$instance ??= new CoreDebugger(
            self::$history,
            self::$enabled,
            self::$sessionKey
        );
    }

    /**
     * Set the Debugger instance to use
     * @param CoreDebugger $instance
     * @return void
     */
    public static function setInstance(CoreDebugger $instance): void
    {
        self::$instance = $instance;
    }

    public static function isEnabled(): bool
    {
        $instance = self::getInstance();
        return $instance->isEnabled();
    }

    public static function logSession(string $title): void
    {
        $instance = self::getInstance();
        $instance->logSession($title);
    }

    public static function set(string $key, mixed $value): void
    {
        $instance = self::getInstance();
        $instance->set($key, $value);
    }

    public static function add(string $key, mixed $value): void
    {
        $instance = self::getInstance();
        $instance->add($key, $value);
    }

    public static function get(string $key): mixed
    {
        $instance = self::getInstance();
        return $instance->get($key);
    }

    public static function end(string $type): void
    {
        $instance = self::getInstance();
        $instance->end($type);
    }

    public static function toolbar(): void
    {
        $instance = self::getInstance();
        $instance->toolbar();
    }

    /** @param array<object> $objects */
    public static function debug(mixed $variable, int $strlen = 100, int $width = 25, int $depth = 10, int $i = 0, array &$objects = []): ?string
    {
        $instance = self::getInstance();
        return $instance->debug($variable, $strlen, $width, $depth, $i, $objects);
    }
}
