<?php

/**
 * WARNING: This is a generated wrapper file.
 * Do not edit this file manually as changes will be overwritten
 * by the wrapper generator (generate_wrappers.php).
 * 
 * To modify this class, edit the corresponding Core class in src/Core/
 * and regenerate the wrappers.
 */

namespace MintyPHP;

use MintyPHP\Core\Debugger as CoreDebugger;

/**
 * Debugger class for development and debugging support.
 * 
 * Provides comprehensive debugging capabilities including request logging,
 * query tracking, session inspection, and performance monitoring.
 */
class Debugger
{
    /**
     * Static configuration parameters
     */
    public static int $history = 10;
    public static bool $enabled = false;
    public static string $sessionKey = 'debugger';

    /**
     * The Debugger instance
     * @var ?CoreDebugger
     */
    private static ?CoreDebugger $instance = null;

    /**
     * Get the Debugger instance
     * @return CoreDebugger
     */
    public static function getInstance(): CoreDebugger
    {
        return self::$instance ??= new CoreDebugger(
            self::$history,
            self::$enabled,
            self::$sessionKey
        );
    }

    /**
     * Set the Debugger instance to use
     * @param ?CoreDebugger $instance
     * @return void
     */
    public static function setInstance(?CoreDebugger $instance): void
    {
        self::$instance = $instance;
    }

    /**
     * Check if the debugger is enabled
     * @return bool True if enabled, false otherwise
     */
    public static function isEnabled(): bool
    {
        $instance = self::getInstance();
        return $instance->isEnabled();
    }

    /**
     * Add a cache call entry to the debugger log
     * @param float $duration The duration of the cache call
     * @param string $command The cache command executed
     * @param array<mixed> $arguments The arguments passed to the cache command
     * @param mixed $result The result returned from the cache command
     * @return void
     */
    public static function addCacheCall(float $duration, string $command, array $arguments, mixed $result): void
    {
        $instance = self::getInstance();
        $instance->addCacheCall($duration, $command, $arguments, $result);
    }

    /**
     * Add an API call entry to the debugger log
     * @param float $duration The duration of the API call
     * @param string $method The HTTP method used
     * @param string $url The URL called
     * @param array<string,mixed> $data The data sent with the request
     * @param array<string,mixed> $options The options used for the request
     * @param array<string,string> $headers The headers sent with the request
     * @param int $status The HTTP status code returned
     * @param array{nameLookup:float,connect:float,preTransfer:float,startTransfer:float,redirect:float,total:float} $timing The timing information for the call
     * @param mixed $result The result returned from the API call
     * @return void
     */
    public static function addApiCall(float $duration, string $method, string $url, mixed $data, array $options, array $headers, int $status, array $timing, mixed $result): void
    {
        $instance = self::getInstance();
        $instance->addApiCall($duration, $method, $url, $data, $options, $headers, $status, $timing, $result);
    }

    /**
     * Add a query entry to the debugger log
     * @param float $duration The duration of the query
     * @param string $query The SQL query executed
     * @param string $equery The SQL query executed
     * @param array<int|string, mixed> $arguments The arguments passed to the query
     * @param mixed $result The result returned from the query
     * @param mixed $explain The result returned from the query
     * @return void
     */
    public static function addQuery(float $duration, string $query, string $equery, array $arguments, mixed $result, mixed $explain): void
    {
        $instance = self::getInstance();
        $instance->addQuery($duration, $query, $equery, $arguments, $result, $explain);
    }

    /**
     * Set the route information for the current request
     * @param string $method The HTTP method used
     * @param bool $csrfOk Whether CSRF validation passed
     * @param string $request The raw request string
     * @param string $url The requested URL
     * @param string $dir The directory of the request
     * @param string $viewFile The view file used
     * @param string $actionFile The action file used
     * @param string $templateFile The template file used
     * @param array<string,mixed> $urlParameters The URL parameters
     * @param array<string,mixed> $getParameters The GET parameters
     * @param array<string,mixed> $postParameters The POST parameters
     * @return void
     */
    public static function setRoute(string $method, bool $csrfOk, string $request, string $url, string $dir, string $viewFile, string $actionFile, string $templateFile, array $urlParameters, array $getParameters, array $postParameters): void
    {
        $instance = self::getInstance();
        $instance->setRoute($method, $csrfOk, $request, $url, $dir, $viewFile, $actionFile, $templateFile, $urlParameters, $getParameters, $postParameters);
    }

    /**
     * Set the redirect URL for the current request
     * @param string $url The URL to redirect to
     * @return void
     */
    public static function setRedirect(string $url): void
    {
        $instance = self::getInstance();
        $instance->setRedirect($url);
    }

    /**
     * Set the status code for the current request
     * @param int $status The HTTP status code
     * @return void
     */
    public static function setStatus(int $status): void
    {
        $instance = self::getInstance();
        $instance->setStatus($status);
    }

    /**
     * Log the session state before processing the request
     * @return void
     */
    public static function logSessionBefore(): void
    {
        $instance = self::getInstance();
        $instance->logSessionBefore();
    }

    /**
     * Log the session state after processing the request
     * @return void
     */
    public static function logSessionAfter(): void
    {
        $instance = self::getInstance();
        $instance->logSessionAfter();
    }

    /**
     * Get the session key used for storing debugger data
     * @return string The session key
     */
    public static function getSessionKey(): string
    {
        $instance = self::getInstance();
        return $instance->getSessionKey();
    }

    /**
     * Finalize and store the debugger data at the end of the request
     * @param string $type The type of request completion (e.g., 'ok', 'abort')
     * @return void
     */
    public static function end(string $type): void
    {
        $instance = self::getInstance();
        $instance->end($type);
    }

    /**
     * Output the debugger toolbar HTML.
     * @return void
     */
    public static function toolbar(): void
    {
        $instance = self::getInstance();
        $instance->toolbar();
    }

    /**
     * Debug a variable and return its string representation.
     * @param mixed $variable The variable to debug
     * @param int $strlen Maximum string length
     * @param int $width Maximum array/object width
     * @param int $depth Maximum depth for nested structures
     * @param int $i Current depth (used internally) 
     * @param array<object> $objects List of already processed objects (used internally)
     * @return string String representation of the variable
     */
    public static function debug(mixed $variable, int $strlen = 100, int $width = 25, int $depth = 10, int $i = 0, array &$objects = []): string
    {
        $instance = self::getInstance();
        return $instance->debug($variable, $strlen, $width, $depth, $i, $objects);
    }
}
