<?php

/**
 * WARNING: This is a generated wrapper file.
 * Do not edit this file manually as changes will be overwritten
 * by the wrapper generator (generate_wrappers.php).
 * 
 * To modify this class, edit the corresponding Core class in src/Core/
 * and regenerate the wrappers.
 */

namespace MintyPHP;

use MintyPHP\Core\Firewall as CoreFirewall;

/**
 * Firewall class for rate limiting and request concurrency control.
 * 
 * Protects your application from abuse by limiting the number of concurrent
 * requests from the same IP address. Uses a spin-lock mechanism with Memcached
 * to ensure requests wait rather than fail immediately.
 */
class Firewall
{
    public static int $concurrency = 10;
    public static float $spinLockSeconds = 0.15;
    public static int $intervalSeconds = 300;
    public static string $cachePrefix = 'fw_concurrency_';
    public static bool $reverseProxy = false;

    /**
     * The Firewall instance
     * @var ?CoreFirewall
     */
    private static ?CoreFirewall $instance = null;

    /**
     * Get the Firewall instance
     * @return CoreFirewall
     */
    public static function getInstance(): CoreFirewall
    {
        return self::$instance ??= new CoreFirewall(
            Cache::getInstance(),
            Debugger::getInstance(),
            self::$concurrency,
            self::$spinLockSeconds,
            self::$intervalSeconds,
            self::$cachePrefix,
            self::$reverseProxy
        );
    }

    /**
     * Set the Firewall instance to use
     * @param CoreFirewall $instance
     * @return void
     */
    public static function setInstance(CoreFirewall $instance): void
    {
        self::$instance = $instance;
    }

    public static function start(): void
    {
        $instance = self::getInstance();
        $instance->start();
    }

    public static function end(): void
    {
        $instance = self::getInstance();
        $instance->end();
    }
}
