<?php

/**
 * WARNING: This is a generated wrapper file.
 * Do not edit this file manually as changes will be overwritten
 * by the wrapper generator (generate_wrappers.php).
 * 
 * To modify this class, edit the corresponding Core class in src/Core/
 * and regenerate the wrappers.
 */

namespace MintyPHP;

use MintyPHP\Core\I18n as CoreI18n;

/**
 * Internationalization and localization for MintyPHP
 * 
 * Provides formatting for currency, dates, times, and translation management
 * for multiple locales.
 */
class I18n
{
    /**
     * Static configuration parameters
     */
    public static string $domain = 'default';
    public static string $locale = '';
    public static string $defaultLocale = 'en';

    /**
     * The I18n instance
     * @var ?CoreI18n
     */
    private static ?CoreI18n $instance = null;

    /**
     * Get the I18n instance
     * @return CoreI18n
     */
    public static function getInstance(): CoreI18n
    {
        return self::$instance ??= new CoreI18n(
            self::$domain,
            self::$locale,
            self::$defaultLocale
        );
    }

    /**
     * Set the I18n instance to use
     * @param ?CoreI18n $instance
     * @return void
     */
    public static function setInstance(?CoreI18n $instance): void
    {
        self::$instance = $instance;
    }

    /**
     * Format a price with currency symbol.
     * 
     * @param float|int|null $price The price value.
     * @param int $minDecimals Minimum number of decimal places.
     * @param int $maxDecimals Maximum number of decimal places.
     * @return string The formatted price string.
     */
    public static function price($price, int $minDecimals = 2, int $maxDecimals = 2): string
    {
        $instance = self::getInstance();
        return $instance->price($price, $minDecimals, $maxDecimals);
    }

    /**
     * Format a currency value without symbol.
     * 
     * @param float|int|null $currency The currency value.
     * @param int $minDecimals Minimum number of decimal places.
     * @param int $maxDecimals Maximum number of decimal places.
     * @return string The formatted currency string.
     */
    public static function currency($currency, int $minDecimals = 2, int $maxDecimals = 2): string
    {
        $instance = self::getInstance();
        return $instance->currency($currency, $minDecimals, $maxDecimals);
    }

    /**
     * Format a date string.
     * 
     * @param string $str The date string to format.
     * @return string The formatted date.
     */
    public static function date(string $str): string
    {
        $instance = self::getInstance();
        return $instance->date($str);
    }

    /**
     * Format a UTC date string.
     * 
     * @param string $str The UTC date string to format.
     * @return string The formatted date.
     */
    public static function dateUtc(string $str): string
    {
        $instance = self::getInstance();
        return $instance->dateUtc($str);
    }

    /**
     * Format a duration in seconds as HH:MM:SS.
     * 
     * @param int $seconds The duration in seconds.
     * @param bool $trim Whether to trim leading zeros.
     * @return string The formatted duration.
     */
    public static function duration(int $seconds, bool $trim = false): string
    {
        $instance = self::getInstance();
        return $instance->duration($seconds, $trim);
    }

    /**
     * Format a datetime string.
     * 
     * @param string $str The datetime string to format.
     * @return string The formatted datetime.
     */
    public static function datetime(string $str): string
    {
        $instance = self::getInstance();
        return $instance->datetime($str);
    }

    /**
     * Format a UTC datetime string.
     * 
     * @param string $str The UTC datetime string to format.
     * @return string The formatted datetime.
     */
    public static function datetimeUtc(string $str): string
    {
        $instance = self::getInstance();
        return $instance->datetimeUtc($str);
    }

    /**
     * Format a time value.
     * 
     * @param int $hours The hours component.
     * @param int $minutes The minutes component.
     * @param int $seconds The seconds component.
     * @return string The formatted time.
     */
    public static function time(int $hours, int $minutes, int $seconds = 0): string
    {
        $instance = self::getInstance();
        return $instance->time($hours, $minutes, $seconds);
    }

    /**
     * Format a UTC time value.
     * 
     * @param int $hours The hours component.
     * @param int $minutes The minutes component.
     * @param int $seconds The seconds component.
     * @return string The formatted time.
     */
    public static function timeUtc(int $hours, int $minutes, int $seconds = 0): string
    {
        $instance = self::getInstance();
        return $instance->timeUtc($hours, $minutes, $seconds);
    }

    /**
     * Get the localized name of a weekday.
     * 
     * @param int $dayOfWeek The day of week (0-7, where 0 and 7 are Sunday).
     * @return string The localized weekday name.
     */
    public static function weekDay(int $dayOfWeek): string
    {
        $instance = self::getInstance();
        return $instance->weekDay($dayOfWeek);
    }

    /**
     * Get the localized name of a month.
     * 
     * @param int $monthOfYear The month number (1-12).
     * @return string The localized month name.
     */
    public static function monthName(int $monthOfYear): string
    {
        $instance = self::getInstance();
        return $instance->monthName($monthOfYear);
    }

    /**
     * Format a datetime string in a shortened format.
     * 
     * Shows year if different from current year, time if within 24 hours,
     * day abbreviation if within 7 days, or day and date otherwise.
     * 
     * @param string $str The datetime string to format.
     * @return string The formatted short datetime.
     */
    public static function datetimeShort(string $str): string
    {
        $instance = self::getInstance();
        return $instance->datetimeShort($str);
    }

    /**
     * Translate a string ID to the localized text.
     * 
     * Loads translation files from i18n/{domain}_{locale}.json on demand.
     * 
     * @param string $id The translation ID.
     * @return string The translated text, or the ID if not found.
     */
    public static function translate(string $id): string
    {
        $instance = self::getInstance();
        return $instance->translate($id);
    }
}
