<?php

/**
 * WARNING: This is a generated wrapper file.
 * Do not edit this file manually as changes will be overwritten
 * by the wrapper generator (generate_wrappers.php).
 * 
 * To modify this class, edit the corresponding Core class in src/Core/
 * and regenerate the wrappers.
 */

namespace MintyPHP;

use MintyPHP\Core\Network as CoreNetwork;

/**
 * Core Network class providing network-related functionalities.
 */
class Network
{
    /**
     * The Network instance
     * @var ?CoreNetwork
     */
    private static ?CoreNetwork $instance = null;

    /**
     * Get the Network instance
     * @return CoreNetwork
     */
    public static function getInstance(): CoreNetwork
    {
        return self::$instance ??= new CoreNetwork(

        );
    }

    /**
     * Set the Network instance to use
     * @param ?CoreNetwork $instance
     * @return void
     */
    public static function setInstance(?CoreNetwork $instance): void
    {
        self::$instance = $instance;
    }

    /**
     * Check if the given IP address is assigned to a local network interface.
     * @param string $ipAddress
     * @return bool
     */
    public static function isLocalIP(string $ipAddress): bool
    {
        $instance = self::getInstance();
        return $instance->isLocalIP($ipAddress);
    }

    /**
     * Check if an IPv4 address is within a given CIDR range.
     * @param string $ip4
     * @param string $range
     * @return bool
     */
    public static function ipv4Match(string $ip4, string $range): bool
    {
        $instance = self::getInstance();
        return $instance->ipv4Match($ip4, $range);
    }

    /**
     * Check if an IPv6 address is within a given CIDR range.
     * @param string $ip6
     * @param string $range
     * @return bool
     */
    public static function ipv6Match(string $ip6, string $range): bool
    {
        $instance = self::getInstance();
        return $instance->ipv6Match($ip6, $range);
    }
}
