<?php

/**
 * WARNING: This is a generated wrapper file.
 * Do not edit this file manually as changes will be overwritten
 * by the wrapper generator (generate_wrappers.php).
 * 
 * To modify this class, edit the corresponding Core class in src/Core/
 * and regenerate the wrappers.
 */

namespace MintyPHP;

use MintyPHP\Core\NoPassAuth as CoreNoPassAuth;

/**
 * Passwordless Authentication for MintyPHP
 * 
 * Provides passwordless user authentication using time-based tokens,
 * with support for remember-me functionality and optional TOTP two-factor authentication.
 */
class NoPassAuth
{
    /**
     * Static configuration parameters
     */
    public static string $usersTable = 'users';
    public static string $usernameField = 'username';
    public static string $passwordField = 'password';
    public static string $rememberTokenField = 'remember_token';
    public static string $rememberExpiresField = 'remember_expires';
    public static string $createdField = 'created';
    public static string $totpSecretField = 'totp_secret';
    public static int $tokenValidity = 300;
    public static int $rememberDays = 90;
    public static string $tokenAlgorithm = 'HS256';
    public static string $sessionName = 'mintyphp';
    public static string $baseUrl = '/';

    /**
     * The NoPassAuth instance
     * @var ?CoreNoPassAuth
     */
    private static ?CoreNoPassAuth $instance = null;

    /**
     * Get the NoPassAuth instance
     * @return CoreNoPassAuth
     */
    public static function getInstance(): CoreNoPassAuth
    {
        return self::$instance ??= new CoreNoPassAuth(
            DB::getInstance(),
            Totp::getInstance(),
            self::$usersTable,
            self::$usernameField,
            self::$passwordField,
            self::$rememberTokenField,
            self::$rememberExpiresField,
            self::$createdField,
            self::$totpSecretField,
            self::$tokenValidity,
            self::$rememberDays,
            self::$tokenAlgorithm,
            self::$sessionName,
            self::$baseUrl
        );
    }

    /**
     * Set the NoPassAuth instance to use
     * @param ?CoreNoPassAuth $instance
     * @return void
     */
    public static function setInstance(?CoreNoPassAuth $instance): void
    {
        self::$instance = $instance;
    }

    /**
     * Generate a token for the given username.
     * 
     * Creates a JWT token containing the username and IP address,
     * using the user's password hash as the secret.
     * 
     * @param string $username The username to generate a token for.
     * @return string The generated token, or empty string if user not found.
     */
    public static function token(string $username): string
    {
        $instance = self::getInstance();
        return $instance->token($username);
    }

    /**
     * Attempt to restore a user session from a remember-me cookie.
     * 
     * Checks for a valid remember-me cookie, verifies the token,
     * and restores the user session if valid.
     * 
     * @return bool True if session was restored, false otherwise.
     */
    public static function remember(): bool
    {
        $instance = self::getInstance();
        return $instance->remember();
    }

    /**
     * Authenticate a user with a token and optional TOTP code.
     * 
     * Verifies the JWT token signature and claims, checks TOTP if configured,
     * regenerates the session, and stores user data in the session.
     * 
     * @param string $token The JWT token to verify.
     * @param bool $rememberMe Whether to set a remember-me cookie.
     * @param string|null $totp Optional TOTP code for two-factor authentication.
     * @return array<string,array<string,mixed>> User data on success, empty array on failure.
     */
    public static function login(string $token, bool $rememberMe = false, ?string $totp = null): array
    {
        $instance = self::getInstance();
        return $instance->login($token, $rememberMe, $totp);
    }

    /**
     * Log out the current user.
     * 
     * Clears all session variables except debugger data,
     * regenerates the session ID, and removes the remember-me cookie.
     * 
     * @return bool Always returns true.
     */
    public static function logout(): bool
    {
        $instance = self::getInstance();
        return $instance->logout();
    }

    /**
     * Register a new user with the given username.
     * 
     * Creates a new user record with a random hashed password.
     * 
     * @param string $username The username to register.
     * @return int The ID of the newly created user.
     */
    public static function register(string $username): int
    {
        $instance = self::getInstance();
        return $instance->register($username);
    }

    /**
     * Update the password for an existing user.
     * 
     * Generates a new random hashed password for the user.
     * 
     * @param string $username The username to update.
     * @return int The number of affected rows.
     */
    public static function update(string $username): int
    {
        $instance = self::getInstance();
        return $instance->update($username);
    }

    /**
     * Update the TOTP secret for a user.
     * 
     * @param string $username The username to update.
     * @param string $secret The TOTP secret to set.
     * @return int The number of affected rows.
     */
    public static function updateTotpSecret(string $username, string $secret): int
    {
        $instance = self::getInstance();
        return $instance->updateTotpSecret($username, $secret);
    }
}
