<?php

/**
 * WARNING: This is a generated wrapper file.
 * Do not edit this file manually as changes will be overwritten
 * by the wrapper generator (generate_wrappers.php).
 * 
 * To modify this class, edit the corresponding Core class in src/Core/
 * and regenerate the wrappers.
 */

namespace MintyPHP;

use MintyPHP\Core\Router as CoreRouter;

/**
 * Static wrapper class for Router operations using a singleton pattern.
 */
class Router
{
    public static string $baseUrl = '/';
    public static string $pageRoot = 'pages/';
    public static string $templateRoot = 'templates/';
    public static bool $executeRedirect = true;
    /** @var array<string, string> */
    public static array $serverGlobal = [];
    /** @var array<string, string> */
    public static array $routes = [];

    /**
     * The Router instance
     * @var ?CoreRouter
     */
    private static ?CoreRouter $instance = null;

    /**
     * Get the Router instance
     * @return CoreRouter
     */
    public static function getInstance(): CoreRouter
    {
        return self::$instance ??= new CoreRouter(
            self::$baseUrl,
            self::$pageRoot,
            self::$templateRoot,
            self::$executeRedirect,
            self::$serverGlobal,
            self::$routes
        );
    }

    /**
     * Set the Router instance to use
     * @param CoreRouter $instance
     * @return void
     */
    public static function setInstance(CoreRouter $instance): void
    {
        self::$instance = $instance;
    }

    /**
    	 * Redirect to a URL
    	 * @param string $url
    	 * @param bool $permanent
    	 * @return void
    	 */
    public static function redirect(string $url, bool $permanent = false): void
    {
        $instance = self::getInstance();
        $instance->redirect($url, $permanent);
    }

    /**
    	 * Output JSON response and terminate execution
    	 * @param mixed $object The object to encode as JSON
    	 * @return void
    	 */
    public static function json(mixed $object): void
    {
        $instance = self::getInstance();
        $instance->json($object);
    }

    /**
    	 * Initiate file download with provided data and terminate execution
    	 * @param string $filename The name of the file to download
    	 * @param string $data The file content data
    	 * @return void
    	 */
    public static function download(string $filename, string $data): void
    {
        $instance = self::getInstance();
        $instance->download($filename, $data);
    }

    /**
    	 * Initiate file download from filesystem and terminate execution
    	 * @param string $filename The name for the downloaded file
    	 * @param string $filepath The path to the file on the filesystem
    	 * @return void
    	 */
    public static function file(string $filename, string $filepath): void
    {
        $instance = self::getInstance();
        $instance->file($filename, $filepath);
    }

    /**
    	 * Apply route mappings to the current request
    	 * @return void
    	 */
    public static function applyRoutes(): void
    {
        $instance = self::getInstance();
        $instance->applyRoutes();
    }

    /**
    	 * Add a route mapping and re-route
    	 * @param string $sourcePath
    	 * @param string $destinationPath
    	 * @return void
    	 */
    public static function addRoute(string $sourcePath, string $destinationPath): void
    {
        $instance = self::getInstance();
        $instance->addRoute($sourcePath, $destinationPath);
    }

    /**
    	 * Get the matched URL path (view or action name with directory)
    	 * @return string The URL path
    	 */
    public static function getUrl(): string
    {
        $instance = self::getInstance();
        return $instance->getUrl();
    }

    /**
    	 * Get the canonical URL with parameters appended
    	 * Removes trailing 'index' from the URL if present
    	 * @return string The canonical URL path
    	 */
    public static function getCanonical(): string
    {
        $instance = self::getInstance();
        return $instance->getCanonical();
    }

    /**
    	 * Get the current request URI
    	 * @return string The request URI
    	 */
    public static function getRequest(): string
    {
        $instance = self::getInstance();
        return $instance->getRequest();
    }

    /**
    	 * Get the matched action file path
    	 * @return string The full path to the action PHP file, or empty string if none
    	 */
    public static function getAction(): string
    {
        $instance = self::getInstance();
        return $instance->getAction();
    }

    /**
    	 * Get the redirect URL if one was set during routing
    	 * @return string|null The redirect URL, or null if no redirect
    	 */
    public static function getRedirect(): ?string
    {
        $instance = self::getInstance();
        return $instance->getRedirect();
    }

    /**
    	 * Get the matched view file path
    	 * @return string The full path to the view PHTML file, or empty string if none
    	 */
    public static function getView(): string
    {
        $instance = self::getInstance();
        return $instance->getView();
    }

    /**
    	 * Get the template view file path if it exists
    	 * @return string The full path to the template PHTML file, or empty string if none
    	 */
    public static function getTemplateView(): string
    {
        $instance = self::getInstance();
        return $instance->getTemplateView();
    }

    /**
    	 * Get the template action file path if it exists
    	 * @return string The full path to the template PHP file, or empty string if none
    	 */
    public static function getTemplateAction(): string
    {
        $instance = self::getInstance();
        return $instance->getTemplateAction();
    }

    /**
    	 * Get parameters extracted from the URL
    	 * @return array<string, string|null>
    	 */
    public static function getParameters(): array
    {
        $instance = self::getInstance();
        return $instance->getParameters();
    }

    /**
    	 * Get the base URL with protocol and host
    	 * Constructs full URL from base path, adding protocol and host if needed
    	 * @return string The complete base URL with trailing slash
    	 */
    public static function getBaseUrl(): string
    {
        $instance = self::getInstance();
        return $instance->getBaseUrl();
    }
}
