<?php

/**
 * WARNING: This is a generated wrapper file.
 * Do not edit this file manually as changes will be overwritten
 * by the wrapper generator (generate_wrappers.php).
 * 
 * To modify this class, edit the corresponding Core class in src/Core/
 * and regenerate the wrappers.
 */

namespace MintyPHP;

use MintyPHP\Core\Session as CoreSession;

/**
 * Session management class for handling PHP sessions with security features.
 * 
 * Provides session initialization, CSRF token management, and secure session
 * configuration with support for debugging mode.
 */
class Session
{
    public static string|false $sessionId = false;
    public static string $sessionName = 'mintyphp';
    public static string $csrfSessionKey = 'csrf_token';
    public static bool $enabled = true;
    public static int $csrfLength = 16;
    public static string $sameSite = 'Lax';

    /**
     * The Session instance
     * @var ?CoreSession
     */
    private static ?CoreSession $instance = null;

    /**
     * Get the Session instance
     * @return CoreSession
     */
    public static function getInstance(): CoreSession
    {
        return self::$instance ??= new CoreSession(
            Debugger::getInstance(),
            self::$sessionId,
            self::$sessionName,
            self::$csrfSessionKey,
            self::$enabled,
            self::$csrfLength,
            self::$sameSite
        );
    }

    /**
     * Set the Session instance to use
     * @param CoreSession $instance
     * @return void
     */
    public static function setInstance(CoreSession $instance): void
    {
        self::$instance = $instance;
    }

    public static function regenerate(): void
    {
        $instance = self::getInstance();
        $instance->regenerate();
    }

    public static function start(): void
    {
        $instance = self::getInstance();
        $instance->start();
    }

    public static function end(): void
    {
        $instance = self::getInstance();
        $instance->end();
    }

    public static function checkCsrfToken(): bool
    {
        $instance = self::getInstance();
        return $instance->checkCsrfToken();
    }

    public static function getCsrfInput(): void
    {
        $instance = self::getInstance();
        $instance->getCsrfInput();
    }
}
