<?php

/**
 * WARNING: This is a generated wrapper file.
 * Do not edit this file manually as changes will be overwritten
 * by the wrapper generator (generate_wrappers.php).
 * 
 * To modify this class, edit the corresponding Core class in src/Core/
 * and regenerate the wrappers.
 */

namespace MintyPHP;

use MintyPHP\Core\Token as CoreToken;

/**
 * JWT Token management class for generating and validating JSON Web Tokens.
 * 
 * Supports multiple algorithms (HS256, HS384, HS512, RS256, RS384, RS512) and
 * provides claim verification including audience, issuer, and expiration.
 */
class Token
{
    /**
     * Static configuration parameters
     */
    public static string $algorithm = 'HS256';
    public static string $secret = '';
    public static int $leeway = 5;
    public static int $ttl = 30;
    public static string $audience = '';
    public static string $issuer = '';
    public static string $algorithms = '';
    public static string $audiences = '';
    public static string $issuers = '';

    /**
     * The Token instance
     * @var ?CoreToken
     */
    private static ?CoreToken $instance = null;

    /**
     * Get the Token instance
     * @return CoreToken
     */
    public static function getInstance(): CoreToken
    {
        return self::$instance ??= new CoreToken(
            self::$algorithm,
            self::$secret,
            self::$leeway,
            self::$ttl,
            self::$audience,
            self::$issuer,
            self::$algorithms,
            self::$audiences,
            self::$issuers
        );
    }

    /**
     * Set the Token instance to use
     * @param ?CoreToken $instance
     * @return void
     */
    public static function setInstance(?CoreToken $instance): void
    {
        self::$instance = $instance;
    }

    /**
     * @return array<string, mixed>|false
     */
    public static function getClaims(string|false $token): array|false
    {
        $instance = self::getInstance();
        return $instance->getClaims($token);
    }

    /**
     * @param array<string, mixed> $claims
     */
    public static function getToken(array $claims): string|false
    {
        $instance = self::getInstance();
        return $instance->getToken($claims);
    }
}
