<?php

/**
 * WARNING: This is a generated wrapper file.
 * Do not edit this file manually as changes will be overwritten
 * by the wrapper generator (generate_wrappers.php).
 * 
 * To modify this class, edit the corresponding Core class in src/Core/
 * and regenerate the wrappers.
 */

namespace MintyPHP;

use MintyPHP\Core\Totp as CoreTotp;

/**
 * Time-based One-Time Password (TOTP) implementation for MintyPHP.
 * 
 * Provides TOTP generation and verification functionality for two-factor authentication.
 * Supports customizable periods, algorithms, and digit lengths according to RFC 6238.
 */
class Totp
{
    /**
     * Static configuration parameters
     */
    public static int $period = 30;
    public static string $algorithm = 'sha1';
    public static int $digits = 6;
    public static int $secretLength = 10;

    /**
     * The Totp instance
     * @var ?CoreTotp
     */
    private static ?CoreTotp $instance = null;

    /**
     * Get the Totp instance
     * @return CoreTotp
     */
    public static function getInstance(): CoreTotp
    {
        return self::$instance ??= new CoreTotp(
            self::$period,
            self::$algorithm,
            self::$digits,
            self::$secretLength
        );
    }

    /**
     * Set the Totp instance to use
     * @param CoreTotp $instance
     * @return void
     */
    public static function setInstance(CoreTotp $instance): void
    {
        self::$instance = $instance;
    }

    /**
     * Generate a random secret key
     * 
     * @return string Base32 encoded secret key
     */
    public static function generateSecret(): string
    {
        $instance = self::getInstance();
        return $instance->generateSecret();
    }

    /**
     * Generate a TOTP URI for QR code generation
     * 
     * @param string $company Company/issuer name
     * @param string $username User identifier
     * @param string $secret Base32 encoded secret key
     * @return string TOTP URI in otpauth:// format
     */
    public static function generateURI(string $company, string $username, string $secret): string
    {
        $instance = self::getInstance();
        return $instance->generateURI($company, $username, $secret);
    }

    /**
     * Verify a TOTP code against a secret
     * 
     * @param string $secret Base32 encoded secret key
     * @param string $otp OTP code to verify
     * @return bool True if the OTP is valid for the current time period
     */
    public static function verify(string $secret, string $otp): bool
    {
        $instance = self::getInstance();
        return $instance->verify($secret, $otp);
    }
}
